# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f652b992e258c03478b463380b23bca70cb9758a3b26c6dd3f5c31a46fd042548ff0176cc6ad3a5e1077c675c6f8bb305a14121ca5c68568318461507d2c94b

test:
  secret_key_base: 8302ca4ce082fa7e37dc5f8c5915609ee6e7c451fb8451aa2c87258f1db6d68759a2cbf50f358bf26847b57525b2caec1d916a7c51ed710b314067b44f25f864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
